on: push
jobs:
  medal_fetch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@master
        with:
          node_version: 14
      - name: Install Dependencies
        run: npm install
      - name: Fetch Medal
        run: node .
      - name: Update and Commit
        run: |
          git --local config user.name "Github Actions"
          git --local config user.email "action@github.com"
          git add -A
          git commit "Update Data"
      - name: Push to Github
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: true
